FROM --platform=linux/amd64 ubuntu:20.04 as builder

RUN apt-get update
RUN DEBIAN_FRONTEND=noninteractive apt-get install -y build-essential

COPY . /cc500
WORKDIR /cc500
RUN gcc cc500.c -o cc500

FROM ubuntu:20.04 as package
COPY --from=builder /cc500/cc500 /
